// Mocks generated by Mockito 5.4.6 from annotations
// in srl_app/test/unit/viewmodels/add_session_view_model_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i16;

import 'package:drift/drift.dart' as _i5;
import 'package:drift/src/runtime/executor/stream_queries.dart' as _i15;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i18;
import 'package:srl_app/data/app_database.dart' as _i6;
import 'package:srl_app/data/database/daos/goal_dao.dart' as _i8;
import 'package:srl_app/data/database/daos/learning_strategy_dao.dart' as _i13;
import 'package:srl_app/data/database/daos/notification_dao.dart' as _i12;
import 'package:srl_app/data/database/daos/session_dao.dart' as _i7;
import 'package:srl_app/data/database/daos/session_instance_dao.dart' as _i10;
import 'package:srl_app/data/database/daos/session_instance_strategy_dao.dart'
    as _i14;
import 'package:srl_app/data/database/daos/settings_dao.dart' as _i11;
import 'package:srl_app/data/database/daos/task_dao.dart' as _i9;
import 'package:srl_app/domain/models/models.dart' as _i4;
import 'package:srl_app/domain/repositories/session_instance_repository.dart'
    as _i2;
import 'package:srl_app/domain/services/add_session_service.dart' as _i17;
import 'package:srl_app/domain/usecases/use_cases.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeSessionInstanceRepository_0 extends _i1.SmartFake
    implements _i2.SessionInstanceRepository {
  _FakeSessionInstanceRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeManangeInstanceUseCase_1 extends _i1.SmartFake
    implements _i3.ManangeInstanceUseCase {
  _FakeManangeInstanceUseCase_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSessionInstanceModel_2 extends _i1.SmartFake
    implements _i4.SessionInstanceModel {
  _FakeSessionInstanceModel_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMigrationStrategy_3 extends _i1.SmartFake
    implements _i5.MigrationStrategy {
  _FakeMigrationStrategy_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$AppDatabaseManager_4 extends _i1.SmartFake
    implements _i6.$AppDatabaseManager {
  _Fake$AppDatabaseManager_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$SessionsTable_5 extends _i1.SmartFake
    implements _i6.$SessionsTable {
  _Fake$SessionsTable_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$GoalsTable_6 extends _i1.SmartFake implements _i6.$GoalsTable {
  _Fake$GoalsTable_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$TasksTable_7 extends _i1.SmartFake implements _i6.$TasksTable {
  _Fake$TasksTable_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$SessionInstancesTable_8 extends _i1.SmartFake
    implements _i6.$SessionInstancesTable {
  _Fake$SessionInstancesTable_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$SettingsTable_9 extends _i1.SmartFake
    implements _i6.$SettingsTable {
  _Fake$SettingsTable_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$NotificationsTable_10 extends _i1.SmartFake
    implements _i6.$NotificationsTable {
  _Fake$NotificationsTable_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$LearningStrategiesTable_11 extends _i1.SmartFake
    implements _i6.$LearningStrategiesTable {
  _Fake$LearningStrategiesTable_11(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$SessionStrategiesTable_12 extends _i1.SmartFake
    implements _i6.$SessionStrategiesTable {
  _Fake$SessionStrategiesTable_12(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$SessionInstanceStrategiesTable_13 extends _i1.SmartFake
    implements _i6.$SessionInstanceStrategiesTable {
  _Fake$SessionInstanceStrategiesTable_13(
    Object parent,
    Invocation parentInvocation,
  ) : super(parent, parentInvocation);
}

class _FakeSessionDao_14 extends _i1.SmartFake implements _i7.SessionDao {
  _FakeSessionDao_14(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGoalDao_15 extends _i1.SmartFake implements _i8.GoalDao {
  _FakeGoalDao_15(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTaskDao_16 extends _i1.SmartFake implements _i9.TaskDao {
  _FakeTaskDao_16(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSessionInstanceDao_17 extends _i1.SmartFake
    implements _i10.SessionInstanceDao {
  _FakeSessionInstanceDao_17(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSettingsDao_18 extends _i1.SmartFake implements _i11.SettingsDao {
  _FakeSettingsDao_18(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeNotificationDao_19 extends _i1.SmartFake
    implements _i12.NotificationDao {
  _FakeNotificationDao_19(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLearningStrategyDao_20 extends _i1.SmartFake
    implements _i13.LearningStrategyDao {
  _FakeLearningStrategyDao_20(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSessionInstanceStrategyDao_21 extends _i1.SmartFake
    implements _i14.SessionInstanceStrategyDao {
  _FakeSessionInstanceStrategyDao_21(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeStreamQueryUpdateRules_22 extends _i1.SmartFake
    implements _i5.StreamQueryUpdateRules {
  _FakeStreamQueryUpdateRules_22(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGeneratedDatabase_23 extends _i1.SmartFake
    implements _i5.GeneratedDatabase {
  _FakeGeneratedDatabase_23(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDriftDatabaseOptions_24 extends _i1.SmartFake
    implements _i5.DriftDatabaseOptions {
  _FakeDriftDatabaseOptions_24(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDatabaseConnection_25 extends _i1.SmartFake
    implements _i5.DatabaseConnection {
  _FakeDatabaseConnection_25(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeQueryExecutor_26 extends _i1.SmartFake implements _i5.QueryExecutor {
  _FakeQueryExecutor_26(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeStreamQueryStore_27 extends _i1.SmartFake
    implements _i15.StreamQueryStore {
  _FakeStreamQueryStore_27(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDatabaseConnectionUser_28 extends _i1.SmartFake
    implements _i5.DatabaseConnectionUser {
  _FakeDatabaseConnectionUser_28(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMigrator_29 extends _i1.SmartFake implements _i5.Migrator {
  _FakeMigrator_29(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFuture_30<T> extends _i1.SmartFake implements _i16.Future<T> {
  _FakeFuture_30(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeInsertStatement_31<T1 extends _i5.Table, D1> extends _i1.SmartFake
    implements _i5.InsertStatement<T1, D1> {
  _FakeInsertStatement_31(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUpdateStatement_32<T extends _i5.Table, D> extends _i1.SmartFake
    implements _i5.UpdateStatement<T, D> {
  _FakeUpdateStatement_32(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSimpleSelectStatement_33<T1 extends _i5.HasResultSet, D>
    extends _i1.SmartFake
    implements _i5.SimpleSelectStatement<T1, D> {
  _FakeSimpleSelectStatement_33(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeJoinedSelectStatement_34<FirstT extends _i5.HasResultSet, FirstD>
    extends _i1.SmartFake
    implements _i5.JoinedSelectStatement<FirstT, FirstD> {
  _FakeJoinedSelectStatement_34(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBaseSelectStatement_35<Row> extends _i1.SmartFake
    implements _i5.BaseSelectStatement<Row> {
  _FakeBaseSelectStatement_35(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDeleteStatement_36<T1 extends _i5.Table, D1> extends _i1.SmartFake
    implements _i5.DeleteStatement<T1, D1> {
  _FakeDeleteStatement_36(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSelectable_37<T> extends _i1.SmartFake implements _i5.Selectable<T> {
  _FakeSelectable_37(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGenerationContext_38 extends _i1.SmartFake
    implements _i5.GenerationContext {
  _FakeGenerationContext_38(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AddSessionService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAddSessionService extends _i1.Mock implements _i17.AddSessionService {
  MockAddSessionService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i16.Future<int> createSessionWithGoalsAndTasks({
    required _i4.SessionModel? session,
    required List<_i4.GoalModel>? goals,
    required List<_i4.TaskModel>? tasks,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createSessionWithGoalsAndTasks, [], {
              #session: session,
              #goals: goals,
              #tasks: tasks,
            }),
            returnValue: _i16.Future<int>.value(0),
          )
          as _i16.Future<int>);

  @override
  _i16.Future<void> updateSessionWithChanges({
    required int? sessionId,
    required _i4.SessionModel? session,
    required List<_i4.GoalModel>? goalsToUpdate,
    required List<_i4.TaskModel>? tasksToUpdate,
    required Set<String>? goalIdsToDelete,
    required Set<String>? taskIdsToDelete,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateSessionWithChanges, [], {
              #sessionId: sessionId,
              #session: session,
              #goalsToUpdate: goalsToUpdate,
              #tasksToUpdate: tasksToUpdate,
              #goalIdsToDelete: goalIdsToDelete,
              #taskIdsToDelete: taskIdsToDelete,
            }),
            returnValue: _i16.Future<void>.value(),
            returnValueForMissingStub: _i16.Future<void>.value(),
          )
          as _i16.Future<void>);
}

/// A class which mocks [GetOrCreateInstanceUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetOrCreateInstanceUseCase extends _i1.Mock
    implements _i3.GetOrCreateInstanceUseCase {
  MockGetOrCreateInstanceUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.SessionInstanceRepository get instanceRepo =>
      (super.noSuchMethod(
            Invocation.getter(#instanceRepo),
            returnValue: _FakeSessionInstanceRepository_0(
              this,
              Invocation.getter(#instanceRepo),
            ),
          )
          as _i2.SessionInstanceRepository);

  @override
  _i3.ManangeInstanceUseCase get manangeInstanceUseCase =>
      (super.noSuchMethod(
            Invocation.getter(#manangeInstanceUseCase),
            returnValue: _FakeManangeInstanceUseCase_1(
              this,
              Invocation.getter(#manangeInstanceUseCase),
            ),
          )
          as _i3.ManangeInstanceUseCase);

  @override
  _i16.Future<_i4.SessionInstanceModel> call({
    required int? sessionId,
    required DateTime? date,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {#sessionId: sessionId, #date: date}),
            returnValue: _i16.Future<_i4.SessionInstanceModel>.value(
              _FakeSessionInstanceModel_2(
                this,
                Invocation.method(#call, [], {
                  #sessionId: sessionId,
                  #date: date,
                }),
              ),
            ),
          )
          as _i16.Future<_i4.SessionInstanceModel>);
}

/// A class which mocks [AppDatabase].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppDatabase extends _i1.Mock implements _i6.AppDatabase {
  MockAppDatabase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get schemaVersion =>
      (super.noSuchMethod(Invocation.getter(#schemaVersion), returnValue: 0)
          as int);

  @override
  _i5.MigrationStrategy get migration =>
      (super.noSuchMethod(
            Invocation.getter(#migration),
            returnValue: _FakeMigrationStrategy_3(
              this,
              Invocation.getter(#migration),
            ),
          )
          as _i5.MigrationStrategy);

  @override
  _i6.$AppDatabaseManager get managers =>
      (super.noSuchMethod(
            Invocation.getter(#managers),
            returnValue: _Fake$AppDatabaseManager_4(
              this,
              Invocation.getter(#managers),
            ),
          )
          as _i6.$AppDatabaseManager);

  @override
  _i6.$SessionsTable get sessions =>
      (super.noSuchMethod(
            Invocation.getter(#sessions),
            returnValue: _Fake$SessionsTable_5(
              this,
              Invocation.getter(#sessions),
            ),
          )
          as _i6.$SessionsTable);

  @override
  _i6.$GoalsTable get goals =>
      (super.noSuchMethod(
            Invocation.getter(#goals),
            returnValue: _Fake$GoalsTable_6(this, Invocation.getter(#goals)),
          )
          as _i6.$GoalsTable);

  @override
  _i6.$TasksTable get tasks =>
      (super.noSuchMethod(
            Invocation.getter(#tasks),
            returnValue: _Fake$TasksTable_7(this, Invocation.getter(#tasks)),
          )
          as _i6.$TasksTable);

  @override
  _i6.$SessionInstancesTable get sessionInstances =>
      (super.noSuchMethod(
            Invocation.getter(#sessionInstances),
            returnValue: _Fake$SessionInstancesTable_8(
              this,
              Invocation.getter(#sessionInstances),
            ),
          )
          as _i6.$SessionInstancesTable);

  @override
  _i6.$SettingsTable get settings =>
      (super.noSuchMethod(
            Invocation.getter(#settings),
            returnValue: _Fake$SettingsTable_9(
              this,
              Invocation.getter(#settings),
            ),
          )
          as _i6.$SettingsTable);

  @override
  _i6.$NotificationsTable get notifications =>
      (super.noSuchMethod(
            Invocation.getter(#notifications),
            returnValue: _Fake$NotificationsTable_10(
              this,
              Invocation.getter(#notifications),
            ),
          )
          as _i6.$NotificationsTable);

  @override
  _i6.$LearningStrategiesTable get learningStrategies =>
      (super.noSuchMethod(
            Invocation.getter(#learningStrategies),
            returnValue: _Fake$LearningStrategiesTable_11(
              this,
              Invocation.getter(#learningStrategies),
            ),
          )
          as _i6.$LearningStrategiesTable);

  @override
  _i6.$SessionStrategiesTable get sessionStrategies =>
      (super.noSuchMethod(
            Invocation.getter(#sessionStrategies),
            returnValue: _Fake$SessionStrategiesTable_12(
              this,
              Invocation.getter(#sessionStrategies),
            ),
          )
          as _i6.$SessionStrategiesTable);

  @override
  _i6.$SessionInstanceStrategiesTable get sessionInstanceStrategies =>
      (super.noSuchMethod(
            Invocation.getter(#sessionInstanceStrategies),
            returnValue: _Fake$SessionInstanceStrategiesTable_13(
              this,
              Invocation.getter(#sessionInstanceStrategies),
            ),
          )
          as _i6.$SessionInstanceStrategiesTable);

  @override
  _i7.SessionDao get sessionDao =>
      (super.noSuchMethod(
            Invocation.getter(#sessionDao),
            returnValue: _FakeSessionDao_14(
              this,
              Invocation.getter(#sessionDao),
            ),
          )
          as _i7.SessionDao);

  @override
  _i8.GoalDao get goalDao =>
      (super.noSuchMethod(
            Invocation.getter(#goalDao),
            returnValue: _FakeGoalDao_15(this, Invocation.getter(#goalDao)),
          )
          as _i8.GoalDao);

  @override
  _i9.TaskDao get taskDao =>
      (super.noSuchMethod(
            Invocation.getter(#taskDao),
            returnValue: _FakeTaskDao_16(this, Invocation.getter(#taskDao)),
          )
          as _i9.TaskDao);

  @override
  _i10.SessionInstanceDao get sessionInstanceDao =>
      (super.noSuchMethod(
            Invocation.getter(#sessionInstanceDao),
            returnValue: _FakeSessionInstanceDao_17(
              this,
              Invocation.getter(#sessionInstanceDao),
            ),
          )
          as _i10.SessionInstanceDao);

  @override
  _i11.SettingsDao get settingsDao =>
      (super.noSuchMethod(
            Invocation.getter(#settingsDao),
            returnValue: _FakeSettingsDao_18(
              this,
              Invocation.getter(#settingsDao),
            ),
          )
          as _i11.SettingsDao);

  @override
  _i12.NotificationDao get notificationDao =>
      (super.noSuchMethod(
            Invocation.getter(#notificationDao),
            returnValue: _FakeNotificationDao_19(
              this,
              Invocation.getter(#notificationDao),
            ),
          )
          as _i12.NotificationDao);

  @override
  _i13.LearningStrategyDao get learningStrategyDao =>
      (super.noSuchMethod(
            Invocation.getter(#learningStrategyDao),
            returnValue: _FakeLearningStrategyDao_20(
              this,
              Invocation.getter(#learningStrategyDao),
            ),
          )
          as _i13.LearningStrategyDao);

  @override
  _i14.SessionInstanceStrategyDao get sessionInstanceStrategyDao =>
      (super.noSuchMethod(
            Invocation.getter(#sessionInstanceStrategyDao),
            returnValue: _FakeSessionInstanceStrategyDao_21(
              this,
              Invocation.getter(#sessionInstanceStrategyDao),
            ),
          )
          as _i14.SessionInstanceStrategyDao);

  @override
  Iterable<_i5.TableInfo<_i5.Table, Object?>> get allTables =>
      (super.noSuchMethod(
            Invocation.getter(#allTables),
            returnValue: <_i5.TableInfo<_i5.Table, Object?>>[],
          )
          as Iterable<_i5.TableInfo<_i5.Table, Object?>>);

  @override
  List<_i5.DatabaseSchemaEntity> get allSchemaEntities =>
      (super.noSuchMethod(
            Invocation.getter(#allSchemaEntities),
            returnValue: <_i5.DatabaseSchemaEntity>[],
          )
          as List<_i5.DatabaseSchemaEntity>);

  @override
  _i5.StreamQueryUpdateRules get streamUpdateRules =>
      (super.noSuchMethod(
            Invocation.getter(#streamUpdateRules),
            returnValue: _FakeStreamQueryUpdateRules_22(
              this,
              Invocation.getter(#streamUpdateRules),
            ),
          )
          as _i5.StreamQueryUpdateRules);

  @override
  _i5.GeneratedDatabase get attachedDatabase =>
      (super.noSuchMethod(
            Invocation.getter(#attachedDatabase),
            returnValue: _FakeGeneratedDatabase_23(
              this,
              Invocation.getter(#attachedDatabase),
            ),
          )
          as _i5.GeneratedDatabase);

  @override
  _i5.DriftDatabaseOptions get options =>
      (super.noSuchMethod(
            Invocation.getter(#options),
            returnValue: _FakeDriftDatabaseOptions_24(
              this,
              Invocation.getter(#options),
            ),
          )
          as _i5.DriftDatabaseOptions);

  @override
  _i5.DatabaseConnection get connection =>
      (super.noSuchMethod(
            Invocation.getter(#connection),
            returnValue: _FakeDatabaseConnection_25(
              this,
              Invocation.getter(#connection),
            ),
          )
          as _i5.DatabaseConnection);

  @override
  _i5.SqlTypes get typeMapping =>
      (super.noSuchMethod(
            Invocation.getter(#typeMapping),
            returnValue: _i18.dummyValue<_i5.SqlTypes>(
              this,
              Invocation.getter(#typeMapping),
            ),
          )
          as _i5.SqlTypes);

  @override
  _i5.QueryExecutor get executor =>
      (super.noSuchMethod(
            Invocation.getter(#executor),
            returnValue: _FakeQueryExecutor_26(
              this,
              Invocation.getter(#executor),
            ),
          )
          as _i5.QueryExecutor);

  @override
  _i15.StreamQueryStore get streamQueries =>
      (super.noSuchMethod(
            Invocation.getter(#streamQueries),
            returnValue: _FakeStreamQueryStore_27(
              this,
              Invocation.getter(#streamQueries),
            ),
          )
          as _i15.StreamQueryStore);

  @override
  _i5.DatabaseConnectionUser get resolvedEngine =>
      (super.noSuchMethod(
            Invocation.getter(#resolvedEngine),
            returnValue: _FakeDatabaseConnectionUser_28(
              this,
              Invocation.getter(#resolvedEngine),
            ),
          )
          as _i5.DatabaseConnectionUser);

  @override
  _i5.Migrator createMigrator() =>
      (super.noSuchMethod(
            Invocation.method(#createMigrator, []),
            returnValue: _FakeMigrator_29(
              this,
              Invocation.method(#createMigrator, []),
            ),
          )
          as _i5.Migrator);

  @override
  _i16.Future<void> beforeOpen(
    _i5.QueryExecutor? executor,
    _i5.OpeningDetails? details,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#beforeOpen, [executor, details]),
            returnValue: _i16.Future<void>.value(),
            returnValueForMissingStub: _i16.Future<void>.value(),
          )
          as _i16.Future<void>);

  @override
  _i16.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i16.Future<void>.value(),
            returnValueForMissingStub: _i16.Future<void>.value(),
          )
          as _i16.Future<void>);

  @override
  _i16.Future<Ret> computeWithDatabase<Ret, DB extends _i5.GeneratedDatabase>({
    required _i16.FutureOr<Ret> Function(DB)? computation,
    required DB Function(_i5.DatabaseConnection)? connect,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#computeWithDatabase, [], {
              #computation: computation,
              #connect: connect,
            }),
            returnValue:
                _i18.ifNotNull(
                  _i18.dummyValueOrNull<Ret>(
                    this,
                    Invocation.method(#computeWithDatabase, [], {
                      #computation: computation,
                      #connect: connect,
                    }),
                  ),
                  (Ret v) => _i16.Future<Ret>.value(v),
                ) ??
                _FakeFuture_30<Ret>(
                  this,
                  Invocation.method(#computeWithDatabase, [], {
                    #computation: computation,
                    #connect: connect,
                  }),
                ),
          )
          as _i16.Future<Ret>);

  @override
  _i16.Stream<T> createStream<T extends Object>(
    _i15.QueryStreamFetcher<T>? stmt,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createStream, [stmt]),
            returnValue: _i16.Stream<T>.empty(),
          )
          as _i16.Stream<T>);

  @override
  T alias<T, D>(_i5.ResultSetImplementation<T, D>? table, String? alias) =>
      (super.noSuchMethod(
            Invocation.method(#alias, [table, alias]),
            returnValue: _i18.dummyValue<T>(
              this,
              Invocation.method(#alias, [table, alias]),
            ),
          )
          as T);

  @override
  void markTablesUpdated(Iterable<_i5.TableInfo<_i5.Table, dynamic>>? tables) =>
      super.noSuchMethod(
        Invocation.method(#markTablesUpdated, [tables]),
        returnValueForMissingStub: null,
      );

  @override
  void notifyUpdates(Set<_i5.TableUpdate>? updates) => super.noSuchMethod(
    Invocation.method(#notifyUpdates, [updates]),
    returnValueForMissingStub: null,
  );

  @override
  _i16.Stream<Set<_i5.TableUpdate>> tableUpdates([
    _i5.TableUpdateQuery? query = const _i5.TableUpdateQuery.any(),
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#tableUpdates, [query]),
            returnValue: _i16.Stream<Set<_i5.TableUpdate>>.empty(),
          )
          as _i16.Stream<Set<_i5.TableUpdate>>);

  @override
  _i16.Future<T> doWhenOpened<T>(
    _i16.FutureOr<T> Function(_i5.QueryExecutor)? fn,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#doWhenOpened, [fn]),
            returnValue:
                _i18.ifNotNull(
                  _i18.dummyValueOrNull<T>(
                    this,
                    Invocation.method(#doWhenOpened, [fn]),
                  ),
                  (T v) => _i16.Future<T>.value(v),
                ) ??
                _FakeFuture_30<T>(this, Invocation.method(#doWhenOpened, [fn])),
          )
          as _i16.Future<T>);

  @override
  _i5.InsertStatement<T, D> into<T extends _i5.Table, D>(
    _i5.TableInfo<T, D>? table,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#into, [table]),
            returnValue: _FakeInsertStatement_31<T, D>(
              this,
              Invocation.method(#into, [table]),
            ),
          )
          as _i5.InsertStatement<T, D>);

  @override
  _i5.UpdateStatement<Tbl, R> update<Tbl extends _i5.Table, R>(
    _i5.TableInfo<Tbl, R>? table,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#update, [table]),
            returnValue: _FakeUpdateStatement_32<Tbl, R>(
              this,
              Invocation.method(#update, [table]),
            ),
          )
          as _i5.UpdateStatement<Tbl, R>);

  @override
  _i5.SimpleSelectStatement<T, R> select<T extends _i5.HasResultSet, R>(
    _i5.ResultSetImplementation<T, R>? table, {
    bool? distinct = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#select, [table], {#distinct: distinct}),
            returnValue: _FakeSimpleSelectStatement_33<T, R>(
              this,
              Invocation.method(#select, [table], {#distinct: distinct}),
            ),
          )
          as _i5.SimpleSelectStatement<T, R>);

  @override
  _i5.JoinedSelectStatement<T, R> selectOnly<T extends _i5.HasResultSet, R>(
    _i5.ResultSetImplementation<T, R>? table, {
    bool? distinct = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#selectOnly, [table], {#distinct: distinct}),
            returnValue: _FakeJoinedSelectStatement_34<T, R>(
              this,
              Invocation.method(#selectOnly, [table], {#distinct: distinct}),
            ),
          )
          as _i5.JoinedSelectStatement<T, R>);

  @override
  _i5.BaseSelectStatement<_i5.TypedResult> selectExpressions(
    Iterable<_i5.Expression<Object>>? columns,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#selectExpressions, [columns]),
            returnValue: _FakeBaseSelectStatement_35<_i5.TypedResult>(
              this,
              Invocation.method(#selectExpressions, [columns]),
            ),
          )
          as _i5.BaseSelectStatement<_i5.TypedResult>);

  @override
  _i5.DeleteStatement<T, D> delete<T extends _i5.Table, D>(
    _i5.TableInfo<T, D>? table,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [table]),
            returnValue: _FakeDeleteStatement_36<T, D>(
              this,
              Invocation.method(#delete, [table]),
            ),
          )
          as _i5.DeleteStatement<T, D>);

  @override
  _i16.Future<int> customUpdate(
    String? query, {
    List<_i5.Variable<Object>>? variables = const [],
    Set<_i5.ResultSetImplementation<dynamic, dynamic>>? updates,
    _i5.UpdateKind? updateKind,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #customUpdate,
              [query],
              {
                #variables: variables,
                #updates: updates,
                #updateKind: updateKind,
              },
            ),
            returnValue: _i16.Future<int>.value(0),
          )
          as _i16.Future<int>);

  @override
  _i16.Future<int> customInsert(
    String? query, {
    List<_i5.Variable<Object>>? variables = const [],
    Set<_i5.ResultSetImplementation<dynamic, dynamic>>? updates,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #customInsert,
              [query],
              {#variables: variables, #updates: updates},
            ),
            returnValue: _i16.Future<int>.value(0),
          )
          as _i16.Future<int>);

  @override
  _i16.Future<List<_i5.QueryRow>> customWriteReturning(
    String? query, {
    List<_i5.Variable<Object>>? variables = const [],
    Set<_i5.ResultSetImplementation<dynamic, dynamic>>? updates,
    _i5.UpdateKind? updateKind,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #customWriteReturning,
              [query],
              {
                #variables: variables,
                #updates: updates,
                #updateKind: updateKind,
              },
            ),
            returnValue: _i16.Future<List<_i5.QueryRow>>.value(
              <_i5.QueryRow>[],
            ),
          )
          as _i16.Future<List<_i5.QueryRow>>);

  @override
  _i5.Selectable<_i5.QueryRow> customSelect(
    String? query, {
    List<_i5.Variable<Object>>? variables = const [],
    Set<_i5.ResultSetImplementation<dynamic, dynamic>>? readsFrom = const {},
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #customSelect,
              [query],
              {#variables: variables, #readsFrom: readsFrom},
            ),
            returnValue: _FakeSelectable_37<_i5.QueryRow>(
              this,
              Invocation.method(
                #customSelect,
                [query],
                {#variables: variables, #readsFrom: readsFrom},
              ),
            ),
          )
          as _i5.Selectable<_i5.QueryRow>);

  @override
  _i5.Selectable<_i5.QueryRow> customSelectQuery(
    String? query, {
    List<_i5.Variable<Object>>? variables = const [],
    Set<_i5.ResultSetImplementation<dynamic, dynamic>>? readsFrom = const {},
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #customSelectQuery,
              [query],
              {#variables: variables, #readsFrom: readsFrom},
            ),
            returnValue: _FakeSelectable_37<_i5.QueryRow>(
              this,
              Invocation.method(
                #customSelectQuery,
                [query],
                {#variables: variables, #readsFrom: readsFrom},
              ),
            ),
          )
          as _i5.Selectable<_i5.QueryRow>);

  @override
  _i16.Future<void> customStatement(String? statement, [List<dynamic>? args]) =>
      (super.noSuchMethod(
            Invocation.method(#customStatement, [statement, args]),
            returnValue: _i16.Future<void>.value(),
            returnValueForMissingStub: _i16.Future<void>.value(),
          )
          as _i16.Future<void>);

  @override
  _i16.Future<T> transaction<T>(
    _i16.Future<T> Function()? action, {
    bool? requireNew = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #transaction,
              [action],
              {#requireNew: requireNew},
            ),
            returnValue:
                _i18.ifNotNull(
                  _i18.dummyValueOrNull<T>(
                    this,
                    Invocation.method(
                      #transaction,
                      [action],
                      {#requireNew: requireNew},
                    ),
                  ),
                  (T v) => _i16.Future<T>.value(v),
                ) ??
                _FakeFuture_30<T>(
                  this,
                  Invocation.method(
                    #transaction,
                    [action],
                    {#requireNew: requireNew},
                  ),
                ),
          )
          as _i16.Future<T>);

  @override
  _i16.Future<T> exclusively<T>(_i16.Future<T> Function()? action) =>
      (super.noSuchMethod(
            Invocation.method(#exclusively, [action]),
            returnValue:
                _i18.ifNotNull(
                  _i18.dummyValueOrNull<T>(
                    this,
                    Invocation.method(#exclusively, [action]),
                  ),
                  (T v) => _i16.Future<T>.value(v),
                ) ??
                _FakeFuture_30<T>(
                  this,
                  Invocation.method(#exclusively, [action]),
                ),
          )
          as _i16.Future<T>);

  @override
  _i16.Future<void> batch(
    _i16.FutureOr<void> Function(_i5.Batch)? runInBatch,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#batch, [runInBatch]),
            returnValue: _i16.Future<void>.value(),
            returnValueForMissingStub: _i16.Future<void>.value(),
          )
          as _i16.Future<void>);

  @override
  _i16.Future<T> runWithInterceptor<T>(
    _i16.Future<T> Function()? action, {
    required _i5.QueryInterceptor? interceptor,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #runWithInterceptor,
              [action],
              {#interceptor: interceptor},
            ),
            returnValue:
                _i18.ifNotNull(
                  _i18.dummyValueOrNull<T>(
                    this,
                    Invocation.method(
                      #runWithInterceptor,
                      [action],
                      {#interceptor: interceptor},
                    ),
                  ),
                  (T v) => _i16.Future<T>.value(v),
                ) ??
                _FakeFuture_30<T>(
                  this,
                  Invocation.method(
                    #runWithInterceptor,
                    [action],
                    {#interceptor: interceptor},
                  ),
                ),
          )
          as _i16.Future<T>);

  @override
  _i5.GenerationContext $write(
    _i5.Component? component, {
    bool? hasMultipleTables,
    int? startIndex,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #$write,
              [component],
              {#hasMultipleTables: hasMultipleTables, #startIndex: startIndex},
            ),
            returnValue: _FakeGenerationContext_38(
              this,
              Invocation.method(
                #$write,
                [component],
                {
                  #hasMultipleTables: hasMultipleTables,
                  #startIndex: startIndex,
                },
              ),
            ),
          )
          as _i5.GenerationContext);

  @override
  _i5.GenerationContext $writeInsertable(
    _i5.TableInfo<_i5.Table, dynamic>? table,
    _i5.Insertable<dynamic>? insertable, {
    int? startIndex,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #$writeInsertable,
              [table, insertable],
              {#startIndex: startIndex},
            ),
            returnValue: _FakeGenerationContext_38(
              this,
              Invocation.method(
                #$writeInsertable,
                [table, insertable],
                {#startIndex: startIndex},
              ),
            ),
          )
          as _i5.GenerationContext);

  @override
  String $expandVar(int? start, int? amount) =>
      (super.noSuchMethod(
            Invocation.method(#$expandVar, [start, amount]),
            returnValue: _i18.dummyValue<String>(
              this,
              Invocation.method(#$expandVar, [start, amount]),
            ),
          )
          as String);
}
