// Mocks generated by Mockito 5.4.6 from annotations
// in srl_app/test/unit/viewmodels/home_view_model_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:srl_app/domain/models/session_instance_model.dart' as _i9;
import 'package:srl_app/domain/models/session_with_instance_model.dart' as _i6;
import 'package:srl_app/domain/repositories/session_instance_repository.dart'
    as _i3;
import 'package:srl_app/domain/repositories/session_repository.dart' as _i2;
import 'package:srl_app/domain/usecases/instance/manange_instance_use_case.dart'
    as _i8;
import 'package:srl_app/domain/usecases/session/get_completed_sessions_for_today_use_case.dart'
    as _i7;
import 'package:srl_app/domain/usecases/session/get_sessions_for_date_use_case.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeSessionRepository_0 extends _i1.SmartFake
    implements _i2.SessionRepository {
  _FakeSessionRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSessionInstanceRepository_1 extends _i1.SmartFake
    implements _i3.SessionInstanceRepository {
  _FakeSessionInstanceRepository_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GetSessionsForDateUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetSessionsForDateUseCase extends _i1.Mock
    implements _i4.GetSessionsForDateUseCase {
  MockGetSessionsForDateUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Stream<List<_i6.SessionWithInstanceModel>> call(DateTime? date) =>
      (super.noSuchMethod(
            Invocation.method(#call, [date]),
            returnValue: _i5.Stream<List<_i6.SessionWithInstanceModel>>.empty(),
          )
          as _i5.Stream<List<_i6.SessionWithInstanceModel>>);
}

/// A class which mocks [GetCompletedSessionsForTodayUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetCompletedSessionsForTodayUseCase extends _i1.Mock
    implements _i7.GetCompletedSessionsForTodayUseCase {
  MockGetCompletedSessionsForTodayUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.SessionRepository get sessionRepo =>
      (super.noSuchMethod(
            Invocation.getter(#sessionRepo),
            returnValue: _FakeSessionRepository_0(
              this,
              Invocation.getter(#sessionRepo),
            ),
          )
          as _i2.SessionRepository);

  @override
  _i3.SessionInstanceRepository get instanceRepo =>
      (super.noSuchMethod(
            Invocation.getter(#instanceRepo),
            returnValue: _FakeSessionInstanceRepository_1(
              this,
              Invocation.getter(#instanceRepo),
            ),
          )
          as _i3.SessionInstanceRepository);

  @override
  _i5.Stream<List<_i6.SessionWithInstanceModel>> call(DateTime? date) =>
      (super.noSuchMethod(
            Invocation.method(#call, [date]),
            returnValue: _i5.Stream<List<_i6.SessionWithInstanceModel>>.empty(),
          )
          as _i5.Stream<List<_i6.SessionWithInstanceModel>>);
}

/// A class which mocks [ManangeInstanceUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockManangeInstanceUseCase extends _i1.Mock
    implements _i8.ManangeInstanceUseCase {
  MockManangeInstanceUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.SessionInstanceRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeSessionInstanceRepository_1(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i3.SessionInstanceRepository);

  @override
  _i2.SessionRepository get sessionRepository =>
      (super.noSuchMethod(
            Invocation.getter(#sessionRepository),
            returnValue: _FakeSessionRepository_0(
              this,
              Invocation.getter(#sessionRepository),
            ),
          )
          as _i2.SessionRepository);

  @override
  _i5.Future<int> createInstance(_i9.SessionInstanceModel? instance) =>
      (super.noSuchMethod(
            Invocation.method(#createInstance, [instance]),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<int> updateInstance(_i9.SessionInstanceModel? updatedInstance) =>
      (super.noSuchMethod(
            Invocation.method(#updateInstance, [updatedInstance]),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<void> deleteInstanceBySessionId(int? sessionId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteInstanceBySessionId, [sessionId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> deleteInstanceById(int? instanceId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteInstanceById, [instanceId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}
